title: Ajinkya Koshti # your name (or website title) here
logo: "/images/picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Ajinkya, I'm a data scientist located in Ames, IA.
  I hold expertise in building state-of-the-art machine learning models & executing scalable cloud solutions. For more details, check out the About Me section.
  <br><br>
  <a href="https://www.linkedin.com/in/koshti/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
