title: Ajinkya Koshti # your name (or website title) here
logo: "/images/picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Ajinkya, I'm a data scientist located in Ames, IA.
  I hold strong expertise in building state-of-the-art machine learning models & executing scalable cloud solutions. During my past stints, I helped a healthcare company achieve $9.2 million in increased investment returns, an agricultural company save 5% of global crop loss and contributed to open source projects helping physicians to predict aggressiveness of cancer.
  <br><br>
  <a href="https://www.linkedin.com/in/koshti/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
