title: Ajinkya Koshti # your name (or website title) here
logo: "/images/picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Ajinkya, I'm a data scientist located in Ames, IA, United States.
  I have a strong expertise in building state-of-the-art machine learning models & executing scalable cloud solutions. During my past stints, I helped companies in healthcare, finance and genetics identify cost-reduction opportunities and increase income with the help of advanced data analytics.
  <br><br>
  <a href="https://www.linkedin.com/in/koshti/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
